### ISSUE TITLE
ANGLE build produces inconsistent include/GLES2

### ISSUE THREAD

**Issue by treeswift** [armdevvel/mxe#14]
Full log:
https://gist.github.com/pahaze/7c0dae6cc01d36b0464b286771674e84

```
install -d '/home/pahaze/mxe/usr/armv7-w64-mingw32/share/angle' && install -m 644 '/home/pahaze/mxe/tmp-angle-armv7-w64-mingw32/angle-d15be77864e18f407c317be6f6bc06ee2b7d070a/LICENSE' '/home/pahaze/mxe/usr/armv7-w64-mingw32/share/angle/copyright'
'armv7-w64-mingw32-g++' -W -Wall '/home/pahaze/mxe/src/angle-test.cpp' -o '/home/pahaze/mxe/usr/armv7-w64-mingw32/bin/test-angle.exe' `'armv7-w64-mingw32-pkg-config' egl --cflags --libs` `'armv7-w64-mingw32-pkg-config' glesv2 --cflags --libs` -lkernel32
/home/pahaze/mxe/src/angle-test.cpp:89:9: warning: unused variable 'row' [-Wunused-variable]
    int row, column = 0;
        ^
/home/pahaze/mxe/src/angle-test.cpp:89:14: warning: unused variable 'column' [-Wunused-variable]
    int row, column = 0;
             ^
In file included from /home/pahaze/mxe/src/angle-test.cpp:222:
In file included from /home/pahaze/mxe/usr/armv7-w64-mingw32/include/GLES2/gl2ext.h:3943:
In file included from /home/pahaze/mxe/usr/armv7-w64-mingw32/include/GLES2/gl2ext_angle.h:417:
/home/pahaze/mxe/usr/armv7-w64-mingw32/include/GLES2/gl2ext_explicit_context_autogen.inc:182:92: error: unknown type name 'GLDEBUGPROCKHR'; did you mean 'EGLDEBUGPROCKHR'?
typedef void (GL_APIENTRYP PFNGLDEBUGMESSAGECALLBACKKHRCONTEXTANGLEPROC)(GLeglContext ctx, GLDEBUGPROCKHR callback, const void *userParam);
                                                                                           ^
/home/pahaze/mxe/usr/armv7-w64-mingw32/include/EGL/eglext.h:94:29: note: 'EGLDEBUGPROCKHR' declared here
typedef void (EGLAPIENTRY  *EGLDEBUGPROCKHR)(EGLenum error,const char *command,EGLint messageType,EGLLabelKHR threadLabel,EGLLabelKHR objectLabel,const char* message);
                            ^
/home/pahaze/mxe/src/angle-test.cpp:479:12: warning: unused variable 'count' [-Wunused-variable]
    EGLint count, chosenMode;
           ^
/home/pahaze/mxe/src/angle-test.cpp:479:19: warning: unused variable 'chosenMode' [-Wunused-variable]
    EGLint count, chosenMode;
                  ^
/home/pahaze/mxe/src/angle-test.cpp:644:17: warning: unused variable 'hdc' [-Wunused-variable]
            HDC hdc = BeginPaint(hwnd, &ps);
                ^
5 warnings and 1 error generated.
make[1]: *** [Makefile:843: build-only-angle_armv7-w64-mingw32] Error 1
make[1]: Leaving directory '/home/pahaze/mxe'
```

_Originally posted by @pahaze in https://github.com/armdevvel/mxe/issues/11#issuecomment-1007800550_

**Comment by pahaze** [comment]
Alright, so. Like said, build works fine on laptop but not on desktop. Build environment and distribution/etc is EXACT same. Pop!_OS 21.10, latest updates, etc.

**Comment by pahaze** [comment]
Log from laptop:
https://gist.github.com/pahaze/6ed3df1a2bb174fde482a196ca1739b4

**Comment by treeswift** [comment]
- Is the LLVM toolchain the same? (Mine is the 13.0 release from github.)
- *on the desktop*, can you re-run the last compiler call from the log with the `-E` flag ("stop after preprocessing") and save/attach the output (`-o` file or standard output if run without `-o`)?

**Comment by pahaze** [comment]
> Is the LLVM toolchain the same? (Mine is the 13.0 release from github.)
Yes.
> on the desktop, can you re-run the last compiler call from the log with the -E flag ("stop after preprocessing") and save/attach the output (-o file or standard output if run without -o)?
Yeah, later on today. I gotta be done for the night though. Laptop is at 12% :joy:

**Comment by treeswift** [comment]
Have a good night!

**Comment by pahaze** [comment]
You too! I'll get that to you as soon as possible.

**Comment by pahaze** [comment]
Full log with all bash commands on desktop (make/grep/Py env/pip3 list):
https://gist.github.com/pahaze/f8e258f94fc6bda4ab13515e38e2f758

**Comment by pahaze** [comment]
armv7-w64-mingw32-g++ pre-processing output on the ANGLE test file:
https://gist.github.com/pahaze/f739e1c3bf0a5c4c201955f425ba0942

**Comment by pahaze** [comment]
Okay, so... I switched to plain Ubuntu (wiped Pop! last night), and I'm going to try again. If that fixes it, I'll close the issue and just count it as a corrupt installation causing issues and revert the file change (I've already changed it back to one with no sed commands on my end to be sure). If someone else gets the issue, they can comment here.

**Comment by pahaze** [comment]
Seems to have been Pop!. Sorry about the little mess over this issue :joy:

![image](https://user-images.githubusercontent.com/69173292/149831708-ff323a00-0d5f-4e16-a9e6-bc6b59eea650.png)
