### ISSUE TITLE
suggestion: mention UCRT in the README

### ISSUE THREAD

**Issue by treeswift** [armdevvel/mxe#2]
A minor suggestion: maybe mention in the installation instructions that running the compiled/linked binaries on Windows RT requires Universal CRT libraries from the Windows 10 SDK (Windows Kits\10\Redist\ucrt\DLLs\arm) to be deployed on the target machine -- either in the same folder where the app is installed, or anywhere in the DLL search path. The LLVM toolchain sysroot doesn't provide them.

More info: https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/ (see update from September 11, 2015, in red)

Also, if Windows RT is in testsigning mode, these libraries need to be be signed -- funny enough, they aren't signed by default. I used the same certificate for both (self-signed, valid until 2107), but as far as I understand the testsigning mode, the certs needn't match.

**Comment by pahaze** [comment]
Ah, that's right. I have it included with Otter on the forum (under a secondary reply), never put it here though. I'll do that later.

**Comment by pahaze** [comment]
Updated README and put the file that I shared for Otter (known as "PooCRT") on here under a folder called `resources`
