### ISSUE TITLE
gtk3: glib-compile-resources not generated

### ISSUE THREAD

**Issue by treeswift** [armdevvel/mxe#6]
After a successful glib build (for both the host (x64) and the target (armv7) architectures), the following dangling symlink is generated:

`.../mxe/usr/armv7-w64-mingw32/bin/glib-compile-resources -> .../mxe/usr/x86_64-pc-linux-gnu/bin/glib-compile-resources`

Symlinking `/usr/bin/glib-compile-resources` (i.e. using the distro-provided version, 2.64.6 in my case) into both locations fixed the build for me, for now. However, AFAIU, the resource compiler needs to be generated by the host glib build rather than provided as an external dependency.

Maybe my trial and error builds somehow omitted this target (I can retry a clean build of host GLib if needed).

**Comment by pahaze** [comment]
Nah, you don't need to do a clean build unless you want to, but that was my fault IIRC. The whole --target and --host options still confuse me a bit.

**Comment by pahaze** [comment]
I'll try to check this out later today. I'm getting a new drive, more fun for ARM stuff.

**Comment by pahaze** [comment]
[Fixed by using host version (GTK3 builds fine)](https://github.com/armdevvel/mxe/commit/554c3dec406eab49a4f057df0e549010f92fa0f0)
